### PR TITLE
trim down packages

### PR DESCRIPTION
**Pull request by cjyetman**
only load packages used in this repo, the stress test repo, and the interactive report repo

### CODE REVIEW

**Review by maurolepore — APPROVED** [review]
Yay!
LGTM

**Review by maurolepore — COMMENTED** [review]
@cjyetman, I had to solve a merge conflict following your other PR that touched this file.
It was an easy fix but just in case please check this still looks as you expect.

**Comment by cjyetman** [comment]
yup, I made 2 PRs on the same file a couple minutes apart. I felt they were conceptually different, so better to keep separate.

Your merge fixes look about right to me.

**Pull request merged**
