### PR TITLE
add language and peer group option

### PR DESCRIPTION
**Pull request by Clare2D**

### CODE REVIEW

**Comment by Clare2D** [comment]
Now I need to update the create_interactive_report again as I need the language variable as well. Will do so asap.

**Review by maurolepore — CHANGES_REQUESTED** [review]
I solved merge conflicts and flaged FIXME. I think it's safar for the new arguments to go at the end of the signature -- not at the start.

**Comment by cjyetman** [comment]
seems like we're going in circles now... I just merged a PR in the `create_interactive_report` repo to remove `peergroup` from the function's arguments?

**Comment by cjyetman** [comment]
current version of `create_interactive_report ` does not have the `peergroup` nor the `language` argument, so I definitely do not approve of this change
https://github.com/2DegreesInvesting/create_interactive_report/blob/343c6bcee844a165c6ad220107ff9f2eba603d0c/create_interactive_report.R#L1-L29

**Comment by maurolepore** [comment]
This seems incomplete so I changed it to draft to make it harder to merge by accident.

**Comment by cjyetman** [comment]
New arguments should also preferably have a default value so that existing calls to the function do not fail because they don't explicitly set a value for the new argument, e.g. `peergroup = NULL`

**Comment by Clare2D** [comment]
replace with new one

**Pull request closed without merging**
