### PR TITLE
Add a script for testing, can use local repos

### PR DESCRIPTION
**Pull request by AlexAxthelm**
This script runs the container like Constructiva does, but allows for
the uses of local repos (using flags to specify which repo is which).
not particularly elegant, but I've found it usesful in my testing work
so far.

### CODE REVIEW

**Comment by AlexAxthelm** [comment]
@cjyetman This is an extension of your `run-like-wim.sh`, but uses flags, rather than positional arguments, and then allows the user to also override the repos in the container with local ones (using `--mount`s if needed)

**Review by cjyetman — APPROVED** [review]
cool! have you looked at #498 recently... as far as I know, that's the most up-to-date, most correct version that we have of what Constructive actually does

**Comment by AlexAxthelm** [comment]
It's not working perfectly yet.

**Comment by AlexAxthelm** [comment]
I hate parsing arguments in bash

**Comment by cjyetman** [comment]
glad it's not me LOL

**Comment by AlexAxthelm** [comment]
I've got it working great, except that when I do the last pass to `docker run`, it doesn't pick up the last argument as something that should be passed to the command

**Comment by AlexAxthelm** [comment]
A change that may be worth making is taher than having to do `-r bash -i`, jusst have `-i` imply that we want to run bash

**Pull request merged**
