### PR TITLE
add in number of shares check

### PR DESCRIPTION
**Pull request by Clare2D**
Error occurring due to number of shares being passed through as character not numeric.

I updated this to include some more specifications that remove some recurring warning messages, such as dropping the groups and specifying the merge variable.

### CODE REVIEW

**Comment by Clare2D** [comment]
Not sure what this error message in the checks is about. Any ideas CJ?

**Comment by cjyetman** [comment]
So this will resolve all but the first warning referenced in #436 👍🏻

I don't know what this error in the "Source web-tool scripts" GH Action means exactly... will have to investigate further
```r
Error: Error: Assigned data `as.numeric(portfolio$number_of_shares)` must be compatible with existing data.
✖ Existing data has 2966 rows.
✖ Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
```

**Comment by cjyetman** [comment]
The error in the web tool script occurs because the `portfolio` data.frame does not have a column `number_of_shares` (it has `market_value`). So this code I guess has to be adaptable to only do these checks and coercions if `number_of_shares` exists.

**Review by cjyetman — APPROVED** [review]
seems like that did the trick

**Pull request merged**
