### PR TITLE
Prepare to document workflow

### PR DESCRIPTION
**Pull request by maurolepore**
This PR includes changes originally submitted as multiple commits in #387. I'm moving
the changes here to keep #387 focused on only documenting (not editing) existing code.

The changes are by @Clare2D -- but it has me as an author because I was the one
squashing her commits. (I should have changed the author but I forgot.)

@Clare2D, can you please do this:
1. Confirm these are the changes you want .
2. Explain a bit what this changes do.
3. Request another reviewer.
another reviewer?

### CODE REVIEW

**Comment by maurolepore** [comment]
@Clare2D, out CI pipeline fails to run the web-tool scripts. Is this expected ([example](https://github.com/2DegreesInvesting/PACTA_analysis/pull/388/checks?check_run_id=1871942701))? 

```r
── web_tool_script_1.R ─────────────────────────────────────────────────────────
Error: Error: Problem with `mutate()` input `isin`.
✖ `false` must be a character vector, not a `factor` object.
ℹ Input `isin` is `if_else(!fund_isin %in% fund_data$fund_isin, fund_isin, isin)`.
Backtrace:
     █
  1. ├─global::process_raw_portfolio(...)
  2. │ └─global::calculate_fund_portfolio(...)
  3. │   └─`%>%`(...)
  4. ├─dplyr::mutate(...)
  5. ├─dplyr:::mutate.data.frame(...)
  6. │ └─dplyr:::mutate_cols(.data, ...)
  7. │   ├─base::withCallingHandlers(...)
  8. │   └─mask$eval_all_mutate(quo)
  9. └─dplyr::if_else(...)
 10.   └─dplyr:::replace_with(...)
 11.     └─dplyr:::check_type(val, x, name)
 12.       └─dplyr:::glubort(header, "must be {friendly_type_of(template)}, not {friendly_type_of(x)}.")
 ```

**Comment by Clare2D** [comment]
So indeed, this should not cause the tests to fail - and this seems like it's a strange place for it to fail. Perhaps there is an additional commit caught in this? I did not intend to edit the web_tool_script_1 version. It seems that I hadn't pulled the repo initially before making this commit perhaps? 

Intention of PR:
- Update some superseded code, including changing paste0 to path  
- In the offline portfolio_check_initialisation, replacing the "get and clean" functions with the read in of the fst files. 
- Getting calls to the parameter files functional again

this PR should not affect the functionality of the web_tool_scripts rather just ensure there is a working version of the tool offline.

**Comment by maurolepore** [comment]
Thanks! I did see unexpected behaviour so likely it was me who messed something up. I'll try again: I'll resubmit your original PR with a new commit that removes workflow.Rmd (which alrady lives in its own PR).

**Comment by maurolepore** [comment]
@Clare2D I explored the log a bit and it looks like this PR was indeed out of sync with master.

The parent of the commit `1636380 - styler changes (3 days ago) <Clare2D>` should be `d839991 - (origin/master, master) adapt to changes in create_portfolio_subset (#386) (2 days ago) <CJ Yetman>` but instead its parent is `515ad54 - (origin/min-comp-fin-data) Small changes input check (#370) (5 weeks ago) <Clare2D>`.

image

The PR I'm more interested about is #387 and it might be independent of this PR (at least the checks pass). So I suggest you see what you need from this PR and resubmit in a new PR. I'm happy to help with that. What do you think?

**Comment by Clare2D** [comment]
Thanks Mauro. I will create a new PR in the morning!

**Pull request closed without merging**
