### PR TITLE
setup action to use custom docker image

### PR DESCRIPTION
**Pull request by cjyetman**
first attempt at doing #269

### CODE REVIEW

**Comment by cjyetman** [comment]
@maurolepore I began this PR to test the possibility of running the web tool scripts inside of our custom docker image during the GitHub Actions CI process

what seems to be working so far:
- a host ubuntu 18.04 is spun up and the necessary repos are cloned to it
- an instance of our custom docker is spun up inside the ubuntu 18.04 host
- the repo directories from the ubuntu 18.04 host appear to be properly bound/mounted and available inside the docker instance

I'm gonna stop there for now. Feel free to jump in at any time and make changes here. Or not. 😉

**Comment by cjyetman** [comment]
so, the directories are **not** mounting as expected... something is mounting (empty directories) but not what's intended 

I believe this is because I'm not correctly specifying the source directory to mount in the command in the action. I've tried the following...
```
volumes:
         - PACTA_analysis:/bound
         - setup-gleam/pacta-data:/pacta-data
         - create_interactive_report:/create_interactive_report
         - StressTestingModelDev:/StressTestingModelDev
         - user_results:/user_results
```
```
volumes:
         - $GITHUB_WORKSPACE/PACTA_analysis:/bound
         - $GITHUB_WORKSPACE/pacta-data:/pacta-data
         - $GITHUB_WORKSPACE/create_interactive_report:/create_interactive_report
         - $GITHUB_WORKSPACE/StressTestingModelDev:/StressTestingModelDev
         - $GITHUB_WORKSPACE/user_results:/user_results
```
```
volumes:
         - /github/workspace/PACTA_analysis:/bound
         - /github/workspace/pacta-data:/pacta-data
         - /github/workspace/create_interactive_report:/create_interactive_report
         - /github/workspace/StressTestingModelDev:/StressTestingModelDev
         - /github/workspace/user_results:/user_results
```
```
volumes:
         - /home/runner/work/setup-gleam/setup-gleam/PACTA_analysis:/bound
         - /home/runner/work/setup-gleam/setup-gleam/pacta-data:/pacta-data
         - /home/runner/work/setup-gleam/setup-gleam/create_interactive_report:/create_interactive_report
         - /home/runner/work/setup-gleam/setup-gleam/StressTestingModelDev:/StressTestingModelDev
         - /home/runner/work/setup-gleam/setup-gleam/user_results:/user_results
```
```
volumes:
         - ./PACTA_analysis:/bound
         - ./pacta-data:/pacta-data
         - ./create_interactive_report:/create_interactive_report
         - ./StressTestingModelDev:/StressTestingModelDev
         - ./user_results:/user_results
```
any other ides?

**Comment by cjyetman** [comment]
also tried `${{github.workspace}}` and `${env:GITHUB_WORKSPACE}` with no love ☹️

**Comment by maurolepore** [comment]
I'll close this as it duplicates #297

**Pull request closed without merging**
