### PR TITLE
adapt to current create inteactive report

### PR DESCRIPTION
**Pull request by cjyetman**
adapt to recent changes to the create_interactive_report

depends on #218
depends on 2DegreesInvesting/create_interactive_report/pull/49

has major overlap with #217

### CODE REVIEW

**Comment by cjyetman** [comment]
this all includes changes in #218 

I would prefer that #218 is merged first and then this should be rebased

**Comment by cjyetman** [comment]
FYI... this is in preparation to quickly adapt to changes upstream here 2DegreesInvesting/create_interactive_report/pull/49

**Comment by maurolepore** [comment]
> I would prefer that #218 is merged first and then this should be rebased

Can you edit the first comment to inculde somethign like "Depends on #218"? Comments other than the first one are easy to miss.

**Comment by cjyetman** [comment]
`company_charts_dir` argument has been removed here https://github.com/2DegreesInvesting/create_interactive_report/pull/49/commits/7e79aa5dc3de347118e477db2f7e7d69b1774eca

which will require a change to this PR

**Comment by cjyetman** [comment]
superseded by #217 
closing

**Pull request closed without merging**
