### PR TITLE
add_bics_sector via fin data and bics_bridge data

### PR DESCRIPTION
**Pull request by jacobvjk**
- My previous attempt to re-introduce bics sectors may produce duplicate entries in the portfolio due to non-unique bics entries.
- In this commit I revert to the original idea of using a bics_bridge file to map the holdings and bics sectors.
- the bridge is not complete yet and in general it seems unclear if it is a great choice to use bics, but for the time being, I guess we no alternatives, as this is promised to be part of pacta 2020 afaik.

### CODE REVIEW

**Comment by maurolepore** [comment]
Try `usethis::git_vaccinate()`: https://usethis.r-lib.org/reference/git_vaccinate.html

**Comment by jacobvjk** [comment]
Still not really working.. I mean I don't understand how this is a conflict anyway..

**Comment by maurolepore** [comment]
Now re-reading this thread: https://github.com/2DegreesInvesting/resources/issues/115
...

**Comment by maurolepore** [comment]
So it looks like CJ's last comment is your best bet: https://github.com/2DegreesInvesting/resources/issues/115#issuecomment-608579867

I think:

```
git config --global core.excludesfile .DS_Store
```

**Comment by jacobvjk** [comment]
tired the last one, but this was messy, so I quickly moved it all to a new branch and new PR https://github.com/2DegreesInvesting/PACTA_analysis/pull/78... Closing this one.

**Pull request closed without merging**
