### PR TITLE
data QA markdown 0.1.0

### PR DESCRIPTION
**Pull request by jacobvjk**
@Clare2D since I cannot create new branches on the 2Dii main fork, this would get merged right into master, if I open a PR. Up to you, we can do that. It would not destroy anything, but maybe you could just create another such branch on the 2dii fork off master, so we can merge it into that one instead?

### CODE REVIEW

**Comment by Clare2D** [comment]
I believe I've made the branch. Let me know if that didn't work!

**Comment by Clare2D** [comment]
Although I think merging this automatically into Master is fine. I envisage this as one script that is run at any stage and uses generally the 1_project_init script to set up paths etc. Make sense? Maybe including a check to see that the required files are there as well?

**Comment by jacobvjk** [comment]
Yea, that sounds like a good idea. I will add this functionality before opening the actual PR

**Comment by jacobvjk** [comment]
The files are now being read in automatically from the corresponding PACTA project
I also changed the base branch to "qa"
Will open the PR for review
@Clare2D

**Pull request merged**
