### PR TITLE
sync up arguments

### PR DESCRIPTION
**Pull request by jdhoffa**
Sorry guys, the arguments between PACTA_analysis and create_interactive_report fell out of sync, I think when I reverted 2DegreesInvesting/PACTA_analysis#69

With this PR, and it's counterpart in create_interactive_report, we should be running as normal again.

### CODE REVIEW

**Comment by jdhoffa** [comment]
Locally, `./bin/run-web-tool` now works without error for me:

**Comment by cjyetman** [comment]
@jdhoffa can you revisit this please, given the context of massive PRs just merged to master here and in 2DegreesInvesting/create_interactive_report

**Comment by Clare2D** [comment]
I think these are now superceded.

**Comment by jdhoffa** [comment]
yup looks good, thanks!

**Pull request closed without merging**
