### PR TITLE
test `calculate_fund_portfolio()`

### PR DESCRIPTION
**Pull request by cjyetman**
minimal testing of `calculate_fund_portfolio()`

happy to receive suggestions for improvements

### CODE REVIEW

**Review by maurolepore — APPROVED** [review]
LGTM. 

Maybe protect the formatting of the tribbles by turning off the styler:

```r
# styler: off
tibble::tribble(
  ~x, ~y, ~z,
   1,  2,  3
  )
# styler: on
```

**Comment by cjyetman** [comment]
> Maybe protect the formatting of the tribbles by turning off the styler:
> 
> ```r
> # styler: off
> tibble::tribble(
>   ~x, ~y, ~z,
>    1,  2,  3
>   )
> # styler: on
> ```

Interesting, thanks. @maurolepore can you explain how this works a bit, I'm not familiar with this?

**Comment by maurolepore** [comment]
> You can tell styler to ignore some lines if you want to keep current formatting. You can mark whole blocks or inline expressions with styler: on and styler: off:

-- https://styler.r-lib.org/articles/styler.html#ignoring-certain-lines

``` r
styler::style_text(
  "
  tibble::tribble(
    ~x, ~y, ~z,
     1,  2,  3
    )
  
  # styler: off
  tibble::tribble(
    ~x, ~y, ~z,
     1,  2,  3
    )
  # styler: on
  "
)
#> 
#> tibble::tribble(
#>   ~x, ~y, ~z,
#>   1, 2, 3
#> )
#> 
#>   # styler: off
#>   tibble::tribble(
#>     ~x, ~y, ~z,
#>      1,  2,  3
#>     )
#> # styler: on
```

<sup>Created on 2021-12-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cjyetman** [comment]
thanks... can you tell me if/when/how `styler::style_text()` is forced upon code in this repo?

**Pull request merged**
