### PR TITLE
Remove global env variables from `tdm_utility_functions`

### PR DESCRIPTION
**Pull request by jdhoffa**
I noticed (when running R CMD Check) that some of the functions in `tdm_utility_functions.R` depend on variables in the global environment (ie. variables that are not explicitly defined as function arguments). 

I know this is how a lot of the legacy PACTA code runs, but i think we should be prudent that all new code doesn't rely on this.

### CODE REVIEW

**Review by cjyetman — DISMISSED** [review]
definitely appreciate that strategy 👍🏻

**Comment by cjyetman** [comment]
test fails?

**Review by cjyetman — COMMENTED** [review]
reverting approval until we figure out why the test fails

**Comment by jdhoffa** [comment]
Very confused as to why the check is failing. 

Are these functions called in other repos?

**Comment by cjyetman** [comment]
> Are these functions called in other repos?

yup.... https://github.com/2DegreesInvesting/create_interactive_report/blob/af5a1c91659da022aa0c086b29631f37bb0a67ba/general_en_template/index.Rmd#L45

**Comment by jdhoffa** [comment]
Should be solved now in 2DegreesInvesting/create_interactive_report#464
Unfortunately, the check here will still fail until that PR is merged (and I think actually this PR should be merged first, followed by the downstream PR). 

But you can check out locally and see that it works.

**Review by cjyetman — APPROVED** [review]
^agreed

lgtm

**Comment by cjyetman** [comment]
re-ran tests and they all pass now the 2DegreesInvesting/create_interactive_report#464 is merged

**Pull request merged**
