### PR TITLE
add in call to create_blank_pdf

### PR DESCRIPTION
**Pull request by Clare2D**
This calls in the function in create_interactive_report. It requires https://github.com/2DegreesInvesting/create_interactive_report/pull/382 to be merged.

### CODE REVIEW

**Review by cjyetman — APPROVED** [review]
approved, but still depends on 2DegreesInvesting/create_interactive_report#382 so I prefer that we don't merge this until that is merged

**Comment by Clare2D** [comment]
I've changed this so that the blank file is copied in.

**Comment by cjyetman** [comment]
so, this no longer requires 2DegreesInvesting/create_interactive_report#382, and my approval stands 😁

**Comment by Clare2D** [comment]
Thanks!

**Pull request merged**
