### PR TITLE
Try runnign web tool following Jacob's guide

### PR DESCRIPTION
**Pull request by maurolepore**
This is work in progress. Here I draft an [rmarkdown file](https://github.com/maurolepore/PACTA_analysis/blob/mauro-wip/try-web-tool.md) that implements in code the instructions from the [Google Doc](https://docs.google.com/document/d/1wmSPN_7TnNkB4_wH67XL9tjNXZGrfdTa4F4jWn59v_8/edit) that Jacob wrote.

I intend to check the instructions and help detect potential issues. Eventually I may be able to suggest some ways to simplify or automate the workflow.

### CODE REVIEW

**Comment by jacobvjk** [comment]
@maurolepore does this mean that you got errors when trying to run the webtool script?

re: finding the create_interactive_report(), script 3 sources the function, in case the create_interactive_report repo is n the same location as the PACTA_analysis repo

**Comment by maurolepore** [comment]
Yes, sourcing the first scrip throws `Error: At least one argument must be supplied (input file).n`. But don't worry for now, I still need to explore where this comes from. 

> re: finding the create_interactive_report(), script 3 sources the function, in case the create_interactive_report repo is in the same location as the PACTA_analysis repo

Thanks! 

So we expect this file structure:

```
parent-directory/
|- PACTA_analysis/
|- create_interactive_report/
```

**Comment by jacobvjk** [comment]
> 
> So we expect this file structure:
> 
> ```
> parent-directory/
> |- PACTA_analysis/
> |- create_interactive_report/
> ```

exactly

**Comment by maurolepore** [comment]
I'll close this PR and open a new one. This is to simplify the fork-relationship: Soon I'll re-submit this same PR but from a fork of 2DegreesInvesting rather than of Jacob's fork.

**Pull request closed without merging**
